version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/app/backend
    command: npm start

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: example_password
      MYSQL_DATABASE: transaction_db
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mysql